#!/bin/bash

# Define a pasta de destino onde você deseja copiar os arquivos
DESTINATION_DIR="/c/Users/otavi/OneDrive/Documentos/Web/wordpress/wp-content/plugins/competitive-scheduling"

# Verifica se o diretório existe
if [ ! -d "$DESTINATION_DIR" ]; then
  # Cria o diretório
  echo "Creating the directory: " . "$DESTINATION_DIR";
  mkdir -p "$DESTINATION_DIR"
fi

unset GIT_INDEX_FILE
echo "Start copy files to: " . "$DESTINATION_DIR";

if [ -f "rsync_exclude.txt" ]; then
  exclude_args=""
  while IFS= read -r item; do
    echo "Item lido: $item"
    exclude_args="$exclude_args --exclude '$item'"
  done < "rsync_exclude.txt"
  echo "$exclude_args $DESTINATION_DIR";
fi

echo "End copy";
exit 0;

# Usar arquivo de configuração (rsync_exclude.txt)
if [ -f "rsync_exclude.txt" ]; then
  exclude_args=""
  while IFS= read -r item; do
    exclude_args="$exclude_args --exclude '$item'"
  done < "rsync_exclude.txt"
  # rsync -av $exclude_args . "$DESTINATION_DIR"
  echo "$exclude_args $DESTINATION_DIR";
else
  exclude_list=(
    "node_modules/"
  )
  exclude_args=""
  for item in "${exclude_list[@]}"; do
    exclude_args="$exclude_args --exclude '$item'"
  done
  # rsync -av $exclude_args . "$DESTINATION_DIR"
  echo "not exist!";
fi

echo "End copy";
exit 0;